# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-03 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('connect', '0030_auto_20160505_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFacebookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.TextField()),
                ('extra_data', models.TextField(blank=True)),
                ('token', models.TextField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
                'get_latest_by': 'pk',
                'verbose_name': 'User Facebook Data',
                'verbose_name_plural': 'User Facebook Data',
            },
        ),
    ]
